path: 
  RAW_DATA_PATH: "./data/raw/"
  PROCESSED_DATA_PATH: "./data/processed/"
  ARTIFACTS_PATH: "./research/artifacts/"

dataloader:
  image_path: "./data/raw/dataset.zip"
  image_size: 64
  split_size: 0.40
  batch_size: 1
